spring:
  profiles:
    active: dev
  application:
    name: Order Food

  datasource:
    url: "jdbc:postgresql://localhost:5432/restaurant_db"
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhoang2929@gmail.com
    password: ${emailPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8877

