spring:
  application:
    name: Order Food

  datasource:
    url: "jdbc:postgresql://localhost:5432/restaurant_db"
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

server:
  port: 8877
